const types = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCECCED: "FETCH_COLLECTIONS_SUCCECCED",
    FETCH_COLLECTIONS_FAIL: "FETCH_COLLECTIONS_FAIL"
}

export default types