 const UserActionTypes = {
    SET_CURRENT_USER : "SET_CURRENT_USER",
    SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
    SIGN_IN_WITH_GOOGLE_SUCCECED:'SIGN_IN_WITH_GOOGLE_SUCCECED',
    SIGN_IN_WITH_GOOGLE_FAIL:'SIGN_IN_WITH_GOOGLE_FAIL',
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_START:'SIGN_IN_WITH_EMAIL_AND_PASSWORD_START',
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCECED:'SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCECED',
    SIGN_UP_START:"SIGN_UP_START",
    SIGN_UP_SUCCECED:"SIGN_UP_SUCCECED",
    SIGN_UP_FAIL:"SIGN_UP_FAIL",
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAIL:'SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAIL',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    SET_LOG_IN:"SET_LOG_IN",
    SET_LOG_OUT_START:"SET_LOG_OUT_START",
    SET_LOG_OUT:"SET_LOG_OUT"
}


export default UserActionTypes